version: '3'
services:
  python:
    build: 
      context: ./.devcontainer/python
      dockerfile: Dockerfile
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity

  nodejs:
    build: 
      context: ./.devcontainer/nodejs
      dockerfile: Dockerfile
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity